### ISSUE TITLE
Questions about the models.py

### ISSUE THREAD

**Issue by RashadAlison** [facebookresearch/VisualVoice#6]
------------ Options -------------
audioVisual_feature_dim: 1152
audio_length: 2.55
audio_normalization: True
audio_path: ./test_videos/interview/interview.wav
audio_pool: maxpool
audio_sampling_rate: 16000
batchSize: 32
checkpoints_dir: checkpoints/
compression_type: none
data_path: /private/home/rhgao/datasets/VoxCeleb2/
desired_rms: 0.7
facetrack_root: ./test_videos/interview/faces/
gpu_ids: [0]
hop_length: 2.55
hop_size: 160
hyperbolic_compression_C: 0.1
hyperbolic_compression_K: 10
identity_feature_dim: 128
l2_feature_normalization: False
lipreading_config_path: configs/lrw_snv1x_tcn2x.json
lipreading_extract_feature: True
mask_clip_threshold: 5
mode: test
model: audioVisual
mouthroi_root: ./test_videos/interview/mouthroi/
nThreads: 16
n_fft: 512
name: audioVisual
normalization: True
num_frames: 64
number_of_identity_frames: 1
number_of_speakers: 2
output_dir_root: ./test_videos/interview/
reliable_face: True
seed: 0
sigmoidal_compression_a: 0.1
sigmoidal_compression_b: 0
unet_input_nc: 2
unet_ngf: 64
unet_output_nc: 2
video_sampling_rate: 1
visual_feature_type: both
visual_pool: maxpool
weights_facial: pretrained_models/facial_best.pth
weights_lipreadingnet: pretrained_models/lipreading_best.pth
weights_unet: pretrained_models/unet_best.pth
weights_vocal: pretrained_models/vocal_best.pth
window_size: 400
-------------- End ----------------
Traceback (most recent call last):
  File "/folders/chaopingli/Audio-Visual/Audio-Visual_Speech_Separation_with_Cross-Modal_Consistency/testRealVideo.py", line 230, in <module>
    main()
  File "/folders/chaopingli/Audio-Visual/Audio-Visual_Speech_Separation_with_Cross-Modal_Consistency/testRealVideo.py", line 89, in main
    extract_feats=opt.lipreading_extract_feature)
  File "/folders/chaopingli/Audio-Visual/Audio-Visual_Speech_Separation_with_Cross-Modal_Consistency/models/models.py", line 44, in build_lipreadingnet
    net = Lipreading(tcn_options=tcn_options,
UnboundLocalError: local variable 'tcn_options' referenced before assignment
----------------------------------------------------
I don't know how to solve this, can you help me? please

**Comment by RashadAlison** [comment]
python ./utils/crop_mouth_from_video.py --video-direc ./test_videos/interview/faces/ --landmark-direc ./test_videos/interview/landmark/ --save-direc ./test_videos/interview/mouthroi/ --convert-gray --filename-path ./test_videos/interview/filename_input/interview.csv

So when I run this, I get this.
